# Generated by Django 5.0.6 on 2024-06-25 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_searchresult_user_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('pdf', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.pdf')),
            ],
        ),
    ]
