# Generated by Django 5.0.6 on 2024-06-27 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_pdf_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks',
            name='ref_pdf',
        ),
        migrations.AddField(
            model_name='remarks',
            name='bottom_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remarks',
            name='is_blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remarks',
            name='left_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remarks',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='remarks',
            name='page_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remarks',
            name='page_number_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remarks',
            name='pdf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='page_remarks', to='User.pdf'),
        ),
        migrations.AddField(
            model_name='remarks',
            name='right_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remarks',
            name='top_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PdfRemarkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_pages_count', models.PositiveIntegerField(default=0)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_summary', to='User.pdf')),
            ],
        ),
    ]
