# Generated by Django 5.0.6 on 2024-06-27 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_remarks_ref_pdf_remarks_bottom_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarks',
            name='pdf',
            field=models.ForeignKey(default='random_test.pdf', on_delete=django.db.models.deletion.CASCADE, related_name='page_remarks', to='User.pdf'),
        ),
    ]
