# Generated by Django 5.0.6 on 2024-06-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_remarks_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
