# Generated by Django 5.0.6 on 2024-06-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarks',
            name='page_number',
            field=models.CharField(max_length=20),
        ),
    ]
