# Generated by Django 5.0.6 on 2024-06-28 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_remarks_page_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks',
            name='pdf',
        ),
        migrations.CreateModel(
            name='PdfAnalysisSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_pages_count', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('landscape_pages_count', models.PositiveIntegerField(default=0)),
                ('margin_issues_count', models.PositiveIntegerField(default=0)),
                ('double_sided', models.BooleanField(default=False)),
                ('pdf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_summary', to='User.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('is_blank', models.BooleanField(default=False)),
                ('page_number_location', models.CharField(blank=True, max_length=255, null=True)),
                ('top_margin', models.FloatField(blank=True, null=True)),
                ('left_margin', models.FloatField(blank=True, null=True)),
                ('bottom_margin', models.FloatField(blank=True, null=True)),
                ('right_margin', models.FloatField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], max_length=20, null=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='User.pdf')),
            ],
        ),
        migrations.DeleteModel(
            name='PdfRemarkSummary',
        ),
        migrations.DeleteModel(
            name='Remarks',
        ),
    ]
